source = ~/.config/hypr/variables/layout.conf

general {
    layout = $layout
}

scrolling {
    fullscreen_on_one_column = true
    column_width = 0.90
    focus_fit_method = 0
    follow_focus = true
    follow_min_visible = 1.0
    direction = right
}

bind = $mainMod, A, layoutmsg, move -col
bind = $mainMod, D, layoutmsg, move +col

bind = $mainMod SHIFT, A, layoutmsg, swapcol l
bind = $mainMod SHIFT, D, layoutmsg, swapcol r

bind = $mainMod, minus, layoutmsg, colresize -0.05
bind = $mainMod, equal, layoutmsg, colresize +0.05
bind = $mainMod, F, layoutmsg, fit active

bind = $mainMod, J, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, I, movefocus, u
bind = $mainMod, K, movefocus, d

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

bind = $mainMod, P, pseudo, # dwindle
bind = $mainMod, slash, togglesplit, # dwindle

